services:
  comfyui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUID: "${PUID:-1000}"
        PGID: "${PGID:-1000}"
    image: comfyui-docker:latest
    container_name: comfyui-docker
    ports:
      - "8188:8188"
    volumes:
      - ./entrypoint.sh:/entrypoint.sh:ro
      - ./input:/home/comfy/app/input
      # - ./input/clipspace:/home/comfy/app/input/clipspace/
      # - ./input/pasted:/home/comfy/app/input/pasted/
      - ./custom_nodes:/home/comfy/app/custom_nodes
      - ./models:/home/comfy/app/models
      - ./output:/home/comfy/app/output
      - ./user:/home/comfy/app/user
      - ./.cache:/home/comfy/app/.cache
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - COMFYUI_PATH=/home/comfy/app
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - HF_HOME=/home/comfy/app/.cache/hf_download
      - MODELSCOPE_CACHE=/home/comfy/app/.cache/modelscope
      - U2NET_HOME=/home/comfy/app/models/u2net
      - UPDATE_NODES=${UPDATE_NODES:-false}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    shm_size: 8g
